language: node_js

node_js:
    - "4.1"
    #- "4.0"
    #- "0.12"
    #- "0.11"
    #- "0.10"



sudo: false



git:
    submodules: false



addons:
    apt:
        packages:
            #- php-codesniffer
            #- phpmd
            #- shellcheck



before_script:

    # Install validation tools
    - npm install -g jshint jscs jsonlint uglify-js



script:
    # Check versions of validation tools
    - node --version
    - npm --version
    
    - jscs --version
    - jshint --version
    #- uglifyjs --version
    
    # Run all tests
    - make test



notifications:
    irc: "irc.freenode.org#dbwebb"

    webhooks:
        urls:
            - https://webhooks.gitter.im/e/dc5122e53be3cd85ba1b

        # options: [always|never|change] default: always
        on_success: change
        on_failure: always
        on_start: never
